title:        'Li-Wei Yap'
name:         'Li-Wei Yap'
tagline:      'Software Developer at AnyDesk in Stuttgart, Germany'
description:  'Software Developer at AnyDesk in Stuttgart, Germany'
url:          'https://liweiyap.github.io/'
baseurl:      ''
logo:         'assets/logo-whitesmoke.svg'
image:        'assets/liwei.jpg'

author:
    name:     'Li-Wei Yap'
    email:    'liweiyap@gmail.com'
    github:   'https://github.com/liweiyap'
    linkedin: 'https://www.linkedin.com/in/liweiyap/'
    logo:     'assets/logo-whitesmoke.svg'

plugins:
    - jekyll-seo-tag

preferred_name: 'Li-Wei'
preferred_description:
    en:         'Software Developer'
    de:         'Softwareentwickler'