title:        'Li-Wei Yap'
name:         'Li-Wei Yap'
tagline:      'Software Developer'
description:  'Software Developer'
url:          'https://liweiyap.github.io/'
baseurl:      ''
logo:         'assets/logo-whitesmokelight.svg'
image:        'assets/liwei.jpg'

author:
    name:     'Li-Wei Yap'
    email:    'liweiyap@gmail.com'
    github:   'https://github.com/liweiyap'
    linkedin: 'https://www.linkedin.com/in/liweiyap/'
    logo:     'assets/logo-whitesmokelight.svg'

social:
    name: Li-Wei Yap
    links:
        - https://www.linkedin.com/in/liweiyap
        - https://github.com/liweiyap

plugins:
    - jekyll-seo-tag

preferred_name: 'Li-Wei'
preferred_description:
    en:         'Software Developer'
    de:         'Softwareentwickler'

prog_icons:
    favourites:
        - name: androidstudio
          ext_link: https://developer.android.com/studio
        - name: java
          ext_link: https://www.java.com/en/
        - name: kotlin
          ext_link: https://kotlinlang.org/
        - name: jetpackcompose
          ext_link: https://developer.android.com/jetpack/compose
        - name: git
          ext_link: https://git-scm.com/
        - name: inkscape
          ext_link: https://inkscape.org/
    with_experience:
        - name: cpp
          ext_link: https://en.cppreference.com/w/
        - name: bash
          ext_link: https://www.gnu.org/software/bash/
        - name: python
          ext_link: https://www.python.org/
        - name: qt
          ext_link: https://www.qt.io/
        - name: r
          ext_linK: https://www.r-project.org/
        - name: linux
          ext_link: https://www.linux.org/
    do_not_mind:
        - name: swift
          ext_link: https://swift.org/
        - name: xcode
          ext_link: https://developer.apple.com/xcode/
        - name: css
          ext_link: https://www.w3.org/Style/CSS/
        - name: sqlite
          ext_link: https://www.sqlite.org/index.html
        - name: jekyll
          ext_link: https://jekyllrb.com/
        - name: matlab
          ext_link: https://uk.mathworks.com/products/matlab.html
        - name: gimp
          ext_link: https://www.gimp.org/
        - name: latex
          ext_link: https://www.latex-project.org/
    to_learn:
        - name: javascript
          ext_link: https://en.wikipedia.org/wiki/JavaScript

experience_skills:
    hd:
        - C++
        - Android SDK/NDK
        - Java
        - Git
        - Bash
        - Python
        - Qt
        - CMake
        - Gradle
        - Linux
        - Raspberry Pi
    iq:
        - R
        - Linux
    ic:
        - Matlab

carousels:
    narradir:
        - screenshot-avalon-characterselection
        - screenshot-avalon-play-close
        - screenshot-avalon-play-minions-open
        - screenshot-avalon-play-pause
        - screenshot-avalon-play-minions-close
        - screenshot-avalon-play-merlin
        - screenshot-avalon-play-percival
        - screenshot-avalon-play-wake
        - screenshot-secrethitler-characterselection
        - screenshot-secrethitler-play-fascists
        - screenshot-settings
    text_popover:
        - lightmode
        - darkmode
    xkcdbrowser:
        - screenshot-newestcomic
        - screenshot-404
        - screenshot-dialog-errorhandling
