title:        'Li-Wei'
description:
    en:       'Software Developer'
    de:       'Softwareentwickler'
baseurl:      '/'

author:
    name:     'Li-Wei Yap'
    email:    'liweiyap@gmail.com'
    github:   'https://github.com/liweiyap'
    linkedin: 'https://www.linkedin.com/in/liweiyap/'
